# Generated by Django 4.0.5 on 2022-07-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='asd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
